version: "3"

services:
  proxy-pool-api:
    build: .
    container_name: proxy-pool-api
    restart: always
    ports:
      - 9001:9001
    environment:
      - PROXY_POOL_CONFIG_FILE=/etc/conf.yaml
      - MYSQL_HOST=****
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=****
      - MYSQL_PASSWORD=****
      - MYSQL_DATABASE=proxy_pool
    command: api

  proxy-pool-schduler:
    build: .
    container_name: proxy-pool-scheduler
    restart: always
    environment:
      - PROXY_POOL_CONFIG_FILE=/etc/conf.yaml
      - MYSQL_HOST=****
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=****
      - MYSQL_PASSWORD=****
      - MYSQL_DATABASE=proxy_pool
    command: scheduler