version: "3"

services:
  mysql:
    image: mysql
    container_name: proxy-pool-mysql
    restart: always
    ports:
      - 6003:6003
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proxy_pool

  proxy-pool-api:
    depends_on: 
      - mysql
    image: registry.cn-shanghai.aliyuncs.com/release-lib/proxy-pool 
    container_name: proxy-pool-api
    restart: always
    ports:
      - 9001:9001
    environment:
      - PROXY_POOL_CONFIG_FILE=/etc/conf.yaml
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=proxy_pool
    command: api

  proxy-pool-schduler:
    depends_on: 
      - mysql
    image: registry.cn-shanghai.aliyuncs.com/release-lib/proxy-pool
    container_name: proxy-pool-scheduler
    restart: always
    environment:
      - PROXY_POOL_CONFIG_FILE=/etc/conf.yaml
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=proxy_pool
    command: scheduler