version: "3"

services:
  proxy-pool-api:
    build: .
    container_name: proxy-pool-api
    restart: always
    ports:
      - 9001:9001
    environment:
      - TZ=Asia/Shanghai
      - CONFIG_FILE=/etc/conf.yaml
      - HOST=****
      - PORT=3306
      - USERNAME=****
      - PASSWORD=****
      - DATABASE=proxy_pool
    command: api

  proxy-pool-schduler:
    build: .
    container_name: proxy-pool-scheduler
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - CONFIG_FILE=/etc/conf.yaml
      - HOST=****
      - PORT=3306
      - USERNAME=****
      - PASSWORD=****
      - DATABASE=proxy_pool
    command: scheduler